# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    versioning-strategy: increase
    allow:
      - dependency-name: "tqdm"
      - dependency-name: "h3"
      - dependency-name: "pya5"
      - dependency-name: "dggal"
      - dependency-name: "dggrid4py"
    groups:
      dggs-core:
        patterns:
          - "tqdm"
          - "h3"
          - "pya5"
          - "dggal"
          - "dggrid4py"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
